insert into author (first_name, last_name) values ('Aaron', 'Allston');
insert into author (first_name, last_name) values ('Alastair', 'Reynolds');
insert into author (first_name, last_name) values ('Allen M.', 'Steele');
insert into author (first_name, last_name) values ('Andre', 'Norton');
insert into author (first_name, last_name) values ('Andrew', 'Lang');
insert into author (first_name, last_name) values ('Arthur C.', 'Clarke');
insert into author (first_name, last_name) values ('B.V.', 'Larson');
insert into author (first_name, last_name) values ('Ben', 'Shapiro');
insert into author (first_name, last_name) values ('Betsy', 'Mitchell');
insert into author (first_name, last_name) values ('Bob', 'Mayer');
insert into author (first_name, last_name) values ('Brandon', 'Sanderson');
insert into author (first_name, last_name) values ('Brian', 'Greene');
insert into author (first_name, last_name) values ('Brian', 'Herbert');
insert into author (first_name, last_name) values ('Broken', 'Angels');
insert into author (first_name, last_name) values ('C. E.', 'Murphy');
insert into author (first_name, last_name) values ('Charlaine', 'Harris');
insert into author (first_name, last_name) values ('Christie', 'Golden');
insert into author (first_name, last_name) values ('Craig', 'Alanson');
insert into author (first_name, last_name) values ('Dan', 'Simmons');
insert into author (first_name, last_name) values ('Daniel H.', 'Wilson');
insert into author (first_name, last_name) values ('Dante', 'Alighieri');
insert into author (first_name, last_name) values ('Dennis E.', 'Taylor');
insert into author (first_name, last_name) values ('Diana', 'Rowland');
insert into author (first_name, last_name) values ('Drew', 'Karpyshyn');
insert into author (first_name, last_name) values ('Edgar Rice', 'Burroughs');
insert into author (first_name, last_name) values ('Eric A.', 'Radulski');
insert into author (first_name, last_name) values ('Fritz', 'Leiber');
insert into author (first_name, last_name) values ('Garon', 'Whited');
insert into author (first_name, last_name) values ('Ian R.', 'MacLeod');
insert into author (first_name, last_name) values ('J. R. R.', 'Tolkien');
insert into author (first_name, last_name) values ('J. S.', 'Morin');
insert into author (first_name, last_name) values ('Jack', 'McDevitt');
insert into author (first_name, last_name) values ('Jacqueline A.', 'Eberstein');
insert into author (first_name, last_name) values ('James', 'Luceno');
insert into author (first_name, last_name) values ('Jay', 'Bonansinga');
insert into author (first_name, last_name) values ('Jeremy', 'Robinson');
insert into author (first_name, last_name) values ('Jerry', 'Merritt');
insert into author (first_name, last_name) values ('Jerry', 'Pournelle');
insert into author (first_name, last_name) values ('Joan Frances', 'Turner');
insert into author (first_name, last_name) values ('Joe', 'Schreiber');
insert into author (first_name, last_name) values ('John', 'Barnes');
insert into author (first_name, last_name) values ('John', 'Birmingham');
insert into author (first_name, last_name) values ('John David', 'Krygelski');
insert into author (first_name, last_name) values ('John Jackson', 'Miller');
insert into author (first_name, last_name) values ('John', 'O''Brien');
insert into author (first_name, last_name) values ('John', 'Scalzi');
insert into author (first_name, last_name) values ('John', 'Sonmez');
insert into author (first_name, last_name) values ('Karen', 'Traviss');
insert into author (first_name, last_name) values ('Kevin J.', 'Anderson');
insert into author (first_name, last_name) values ('Kim', 'Harrison');
insert into author (first_name, last_name) values ('Larry', 'Niven');
insert into author (first_name, last_name) values ('Lee', 'Smolin');
insert into author (first_name, last_name) values ('Leonard', 'Susskind');
insert into author (first_name, last_name) values ('Margaret Wander', 'Bonnanno');
insert into author (first_name, last_name) values ('Margaret', 'Weis');
insert into author (first_name, last_name) values ('Mark', 'Tufo');
insert into author (first_name, last_name) values ('Martha', 'Stout');
insert into author (first_name, last_name) values ('Mary C.', 'Vernon');
insert into author (first_name, last_name) values ('Michael', 'Crichton');
insert into author (first_name, last_name) values ('Michael', 'Moorcock');
insert into author (first_name, last_name) values ('Michael', 'Swanwick');
insert into author (first_name, last_name) values ('Michelle', 'Rowen');
insert into author (first_name, last_name) values ('Molly', 'Harper');
insert into author (first_name, last_name) values ('Nancy', 'Kress');
insert into author (first_name, last_name) values ('Paul S.', 'Kemp');
insert into author (first_name, last_name) values ('Peter F.', 'Hamilton');
insert into author (first_name, last_name) values ('R. A.', 'Salvatore');
insert into author (first_name, last_name) values ('R. R.', 'Haywood');
insert into author (first_name, last_name) values ('Rachel', 'Aaron');
insert into author (first_name, last_name) values ('Richard K.', 'Morgan');
insert into author (first_name, last_name) values ('Richard', 'Kadrey');
insert into author (first_name, last_name) values ('Robert C.', 'Atkins');
insert into author (first_name, last_name) values ('Robert', 'Doherty');
insert into author (first_name, last_name) values ('Robert', 'Jordan');
insert into author (first_name, last_name) values ('Robert', 'Kirkman');
insert into author (first_name, last_name) values ('Robert', 'Silverberg');
insert into author (first_name, last_name) values ('Rysa', 'Walker');
insert into author (first_name, last_name) values ('Scott', 'Lynch');
insert into author (first_name, last_name) values ('Sean', 'Williams');
insert into author (first_name, last_name) values ('Stefan', 'Petrucha');
insert into author (first_name, last_name) values ('Stephen', 'Baxter');
insert into author (first_name, last_name) values ('Steven', 'Sherrill');
insert into author (first_name, last_name) values ('TW', 'Brown');
insert into author (first_name, last_name) values ('Terry', 'Pratchett');
insert into author (first_name, last_name) values ('Tim', 'Lebbon');
insert into author (first_name, last_name) values ('Timothy', 'Zahn');
insert into author (first_name, last_name) values ('Tom', 'Purdom');
insert into author (first_name, last_name) values ('Tracy', 'Hickman');
insert into author (first_name, last_name) values ('Travis', 'Adkins');
insert into author (first_name, last_name) values ('Troy', 'Denning');
insert into author (first_name, last_name) values ('Washington', 'Irving');
insert into author (first_name, last_name) values ('Wayne', 'Barlowe');
insert into author (first_name, last_name) values ('Yahtzee', 'Croshaw');
insert into author (first_name, last_name) values ('Z. A.', 'Recht');
