


drop table if exists book;
drop table if exists author;
drop table if exists book_author;


create table book(
    book_id     INT NOT NULL AUTO_INCREMENT,
    title       VARCHAR(200) NOT NULL,
    duration    INT,
    PRIMARY KEY ( book_id )
);


create table author(
    author_id   INT NOT NULL AUTO_INCREMENT,
    first_name  VARCHAR(100),
    last_name   VARCHAR(100),
    PRIMARY KEY ( author_id )
);

create table book_author(
    book_author_id INT NOT NULL AUTO_INCREMENT,
    book_id        INT NOT NULL,
    author_id      INT NOT NULL,
    PRIMARY KEY ( book_author_id )
);



insert into book (title, duration) values ('The Fifth Elephant', '647');
insert into book (title, duration) values ('Columbus Day: Expeditionary Force, Book 1', '983');
insert into book (title, duration) values ('Lycan Fallout 5: Demon Wars', '733');
insert into book (title, duration) values ('Redemption Ark', '1638');
insert into book (title, duration) values ('Salvation: Salvation Sequence, Book 1', '1142');
insert into book (title, duration) values ('Void: Nightlord, Book 5', '2417');
insert into book (title, duration) values ('Hollywood Dead: A Sandman Slim Novel: Sandman Slim Series, Book 10', '563');
insert into book (title, duration) values ('Infinite', '621');
insert into book (title, duration) values ('Valhalla: A Shrouded World, Book 4', '528');
insert into book (title, duration) values ('Etna Station: Zombie Fallout, Book 11', '665');
insert into book (title, duration) values ('The Naked God: Night''s Dawn Trilogy, Book 3', '2917');
insert into book (title, duration) values ('Extinct: Extracted, Book 3', '777');
insert into book (title, duration) values ('Differently Morphous', '623');
insert into book (title, duration) values ('Galaxy Outlaws: The Complete Black Ocean Mobius Missions, 1-16.5', '5106');
insert into book (title, duration) values ('Mogworld', '788');
insert into book (title, duration) values ('Broken Angels', '968');
insert into book (title, duration) values ('A Gift of Time', '706');
insert into book (title, duration) values ('Altered Carbon', '1030');
insert into book (title, duration) values ('The Neutronium Alchemist: The Night''s Dawn Trilogy, Book 2', '2422');
insert into book (title, duration) values ('Executed: Extracted, Book 2', '698');
insert into book (title, duration) values ('Extracted: Extracted, Book 1', '760');
insert into book (title, duration) values ('Defeat''s Victory', '713');

insert into book (title, duration) values ('Bullies: How the Left''s Culture of Fear and Intimidation Silences Americans', '553');
insert into book (title, duration) values ('The Last Continent', '597');
insert into book (title, duration) values ('Convergence: A Shrouded World, Book 3', '531');
insert into book (title, duration) values ('Demon Fallout: The Return', '693');
insert into book (title, duration) values ('Victory''s Defeat', '695');
insert into book (title, duration) values ('Into the Fire', '700');
insert into book (title, duration) values ('From The Ashes', '690');
insert into book (title, duration) values ('We Are Legion (We Are Bob): Bobiverse, Book 1', '571');
insert into book (title, duration) values ('Reckoning', '733');
insert into book (title, duration) values ('Indian Hill', '673');
insert into book (title, duration) values ('DEAD: The Ugly Beginning', '682');
insert into book (title, duration) values ('My Life as a White Trash Zombie', '545');
insert into book (title, duration) values ('The Dangers of Dating a Rebound Vampire', '578');
insert into book (title, duration) values ('Those Left Behind: Zombie Fallout 10', '632');
insert into book (title, duration) values ('The Integral Trees: The State, Book 2', '465');
insert into book (title, duration) values ('Barsoom Series Collection: 7 John Carter Stories', '3271');
insert into book (title, duration) values ('Knightfall: Nightlord, Book 4', '2481');
insert into book (title, duration) values ('Soft Skills: The Software Developer''s Life Manual', '799');
insert into book (title, duration) values ('Timebound', '727');
insert into book (title, duration) values ('Night Shift', '654');
insert into book (title, duration) values ('Tim2: Timothy', '566');
insert into book (title, duration) values ('Hogfather', '586');
insert into book (title, duration) values ('Lycan Fallout 4: Immortality''s Touchstone', '649');
insert into book (title, duration) values ('Taken: A New World, Book 4', '566');
insert into book (title, duration) values ('Feet of Clay', '572');
insert into book (title, duration) values ('Maskerade', '523');

insert into book (title, duration) values ('Interesting Times', '619');
insert into book (title, duration) values ('Revelation Space', '1332');
insert into book (title, duration) values ('Mindstar Rising: The Greg Mandel Trilogy, Book 1', '892');
insert into book (title, duration) values ('A Night Without Stars: A Novel of the Commonwealth: Chronicle of the Fallers Series, Book 2', '1590');
insert into book (title, duration) values ('Orb: Nightlord, Book 3', '2211');
insert into book (title, duration) values ('The Reality Dysfunction: Night''s Dawn Trilogy, Book 1', '2466');
insert into book (title, duration) values ('Soul Music', '671');
insert into book (title, duration) values ('After Twilight: Walking with the Dead', '663');
insert into book (title, duration) values ('Lycan Fallout 3: End of Age', '663');
insert into book (title, duration) values ('Men at Arms', '585');
insert into book (title, duration) values ('Sanctuary: A New World, Book 3', '562');
insert into book (title, duration) values ('Footfall', '1474');
insert into book (title, duration) values ('The Gripping Hand', '911');
insert into book (title, duration) values ('Lords and Ladies', '544');
insert into book (title, duration) values ('Killing Pretty: A Sandman Slim Novel', '587');
insert into book (title, duration) values ('The Abyss Beyond Dreams: Chronicle of the Fallers, Book 1', '1348');
insert into book (title, duration) values ('Starfire', '781');
insert into book (title, duration) values ('Small Gods: Discworld #13', '577');
insert into book (title, duration) values ('RETURN: A New World: Book 2', '554');
insert into book (title, duration) values ('Shadows: Nightlord, Book 2', '2521');
insert into book (title, duration) values ('Witches Abroad', '508');
insert into book (title, duration) values ('Tattered Remnants: Zombie Fallout 9', '689');
insert into book (title, duration) values ('Nightlord: Sunset', '2209');
insert into book (title, duration) values ('Chaos: A New World: Book 1', '492');
insert into book (title, duration) values ('Atlantis: A Shrouded World, Book 2', '570');
insert into book (title, duration) values ('Whistlers: A Shrouded World, Book 1', '498');
insert into book (title, duration) values ('Carrion Comfort', '2367');
insert into book (title, duration) values ('Dune: The Battle of Corrin', '1533');
insert into book (title, duration) values ('The Getaway God: Sandman Slim, Book 6', '662');
insert into book (title, duration) values ('The Snow Women: A Fafhrd and the Gray Mouser Adventure', '203');
insert into book (title, duration) values ('Adept''s Gambit: A Fafhrd and the Gray Mouser Adventure', '232');
insert into book (title, duration) values ('The Lords of Quarmall: A Fafhrd and the Gray Mouser Adventure', '251');
insert into book (title, duration) values ('Rime Isle: A Fafhrd and the Gray Mouser Adventure', '200');
insert into book (title, duration) values ('The Mouser Goes Below: A Fafhrd and the Gray Mouser Adventure', '478');
insert into book (title, duration) values ('The Spirit Clearing: A Michael Talbot Adventure', '552');
insert into book (title, duration) values ('Reaper Man', '515');
insert into book (title, duration) values ('Moving Pictures', '608');
insert into book (title, duration) values ('Lycan Fallout 2: Fall of Man', '676');
insert into book (title, duration) values ('Lycan Fallout: Rise of the Werewolf', '679');
insert into book (title, duration) values ('Eric', '213');
insert into book (title, duration) values ('Guards! Guards!', '607');
insert into book (title, duration) values ('Pyramids: Discworld #7', '555');
insert into book (title, duration) values ('Wyrd Sisters', '626');
insert into book (title, duration) values ('Lords of the Sith: Star Wars', '656');
insert into book (title, duration) values ('Sourcery', '472');
insert into book (title, duration) values ('Mort', '448');
insert into book (title, duration) values ('Zombie Fallout 8: An Old Beginning', '635');
insert into book (title, duration) values ('Zombie Fallout 7: For The Fallen', '655');
insert into book (title, duration) values ('Equal Rites', '462');
insert into book (title, duration) values ('Lucifer''s Hammer', '1472');


insert into book (title, duration) values ('''Til Death Do Us Part: Zombie Fallout, Book 6', '891');
insert into book (title, duration) values ('The Mote in God''s Eye', '1228');
insert into book (title, duration) values ('Zombie Fallout 5: Alive in a Dead World', '666');
insert into book (title, duration) values ('The Light Fantastic: Discworld #2', '414');
insert into book (title, duration) values ('Annihilation: Star Wars: The Old Republic, Book 4', '579');
insert into book (title, duration) values ('The Undead Pool: The Hollows, Book 12', '973');
insert into book (title, duration) values ('Timeless Time Travel Tales', '550');
insert into book (title, duration) values ('The Witch with No Name: The Hollows, Book 13', '1049');
insert into book (title, duration) values ('Star Wars: Dark Lord: The Rise of Darth Vader', '377');
insert into book (title, duration) values ('Star Wars: The Old Republic: Revan', '652');
insert into book (title, duration) values ('The Republic of Thieves: Gentleman Bastard Series, Book 3', '1423');
insert into book (title, duration) values ('Star Trek: Probe (Adapted)', '168');
insert into book (title, duration) values ('Time Cursor', '703');
insert into book (title, duration) values ('Redshirts: A Novel with Three Codas', '461');
insert into book (title, duration) values ('Star Wars: Maul: Lockdown', '740');
insert into book (title, duration) values ('The Fall of the Governor: The Walking Dead, Book 3', '466');
insert into book (title, duration) values ('Star Wars: The Old Republic: Deceived', '565');
insert into book (title, duration) values ('Kenobi: Star Wars Legends', '816');
insert into book (title, duration) values ('Star Wars: Darth Plagueis', '885');
insert into book (title, duration) values ('Dynasty of Evil: A Novel of the Old Republic', '562');
insert into book (title, duration) values ('Rule of Two: Star Wars Legends (Darth Bane)', '612');
insert into book (title, duration) values ('Allegiance: Star Wars Legends', '766');
insert into book (title, duration) values ('Star Wars: Red Harvest', '476');
insert into book (title, duration) values ('Robopocalypse: A Novel', '759');
insert into book (title, duration) values ('Apocalypse: Star Wars Legends (Fate of the Jedi)', '990');
insert into book (title, duration) values ('Path of Destruction: Star Wars Legends (Darth Bane)', '736');
insert into book (title, duration) values ('Into the Void: Star Wars Legends (Dawn of the Jedi)', '623');
insert into book (title, duration) values ('The Care and Feeding of Stray Vampires', '550');
insert into book (title, duration) values ('Star Wars: The Clone Wars: No Prisoners', '430');
insert into book (title, duration) values ('Bloodlust: Nightshade Series, Book 2', '532');
insert into book (title, duration) values ('Free Excerpt: Star Wars: Heir to the Empire - Behind the Scenes', '21');
insert into book (title, duration) values ('A Memory of Light: Wheel of Time, Book 14', '2507');
insert into book (title, duration) values ('Twilight of the Dead', '569');
insert into book (title, duration) values ('The Walking Dead: The Road to Woodbury', '593');
insert into book (title, duration) values ('Urban Shaman: The Walker Papers, Book 1', '610');
insert into book (title, duration) values ('The Colour of Magic: Discworld #1', '416');
insert into book (title, duration) values ('Dust', '596');
insert into book (title, duration) values ('Plague of the Dead: The Morningstar Strain, Book 1', '655');
insert into book (title, duration) values ('World of Ptavvs', '409');
insert into book (title, duration) values ('Time Hunter: The Tunnel at the End of the Light', '204');
insert into book (title, duration) values ('Area 51', '614');
insert into book (title, duration) values ('Time Travelers Never Die', '802');
insert into book (title, duration) values ('The Time Traders', '427');
insert into book (title, duration) values ('Time''s Eye: A Time Odyssey, Book 1', '697');
insert into book (title, duration) values ('Final Impact: Axis of Time, Book 3', '987');
insert into book (title, duration) values ('Designated Targets: Axis of Time, Book 2', '1062');
insert into book (title, duration) values ('Weapons of Choice: Axis of Time, Book 1', '1221');
insert into book (title, duration) values ('God’s Demon', '1023');
insert into book (title, duration) values ('Nightshade: Nightshade Series, Book 1', '557');
insert into book (title, duration) values ('The Minotaur Takes a Cigarette Break: A Novel', '539');



insert into book (title, duration) values ('How to Flirt with a Naked Werewolf', '552');
insert into book (title, duration) values ('Nice Girls Don''t Bite Their Neighbors: Half-Moon Hollow, Book 4', '503');
insert into book (title, duration) values ('Driving Mr. Dead', '332');
insert into book (title, duration) values ('Star Wars: The Old Republic: Fatal Alliance', '827');
insert into book (title, duration) values ('Elric of Melnibone', '330');
insert into book (title, duration) values ('Dragons of the Highlord Skies: The Lost Chronicles, Volume 2', '950');
insert into book (title, duration) values ('Nice Girls Don''t Date Dead Men: Half-Moon Hollow, Book 2', '613');
insert into book (title, duration) values ('Nice Girls Don''t Live Forever: Half-Moon Hollow, Book 3', '538');
insert into book (title, duration) values ('The Art of Seducing a Naked Werewolf', '484');
insert into book (title, duration) values ('Dragons of the Dwarven Depths: The Lost Chronicles, Volume 1', '938');
insert into book (title, duration) values ('Demon Hunts', '655');
insert into book (title, duration) values ('Star Wars: Fate of the Jedi: Conviction', '777');
insert into book (title, duration) values ('Star Wars: Fate of the Jedi: Ascension', '884');
insert into book (title, duration) values ('Nice Girls Don''t Have Fangs: Half-Moon Hollow, Book 1', '528');
insert into book (title, duration) values ('The Trouble with Physics: The Rise of String Theory, The Fall of a Science, and What Comes Next', '889');
insert into book (title, duration) values ('The Black Hole War: My Battle to Make the World Safe for Quantum Mechanics', '765');
insert into book (title, duration) values ('The Spirit Thief', '499');
insert into book (title, duration) values ('Pale Demon: The Hollows, Book 9', '1074');
insert into book (title, duration) values ('Next', '829');
insert into book (title, duration) values ('Early to Death, Early to Rise: Madison Avery, Book 2', '359');
insert into book (title, duration) values ('The Children of Hurin', '471');
insert into book (title, duration) values ('Star Wars: Fate of the Jedi: Vortex', '869');
insert into book (title, duration) values ('Bastion of Darkness', '628');
insert into book (title, duration) values ('The Demon Hunter''s Apprentice', '337');
insert into book (title, duration) values ('The Sociopath Next Door', '446');
insert into book (title, duration) values ('Swords and Ice Magic: The Adventures of Fafhrd and the Gray Mouser', '483');
insert into book (title, duration) values ('The Knight and Knave of Swords: The Adventures of Fafhrd and the Gray Mouser', '755');
insert into book (title, duration) values ('The Elegant Universe: Superstrings, Hidden Dimensions, and the Quest for the Ultimate Theory', '936');
insert into book (title, duration) values ('The Temporal Void: Void Trilogy, Book 2', '1510');
insert into book (title, duration) values ('The Evolutionary Void: Void Trilogy, Book 3', '1485');
insert into book (title, duration) values ('The Great Hunt: Book Two of The Wheel Of Time', '1594');
insert into book (title, duration) values ('The Dreaming Void: Void Trilogy, Book 1', '1355');
insert into book (title, duration) values ('The Divine Comedy', '1023');
insert into book (title, duration) values ('The Eye of the World: Book One of The Wheel of Time', '1797');
insert into book (title, duration) values ('Swords Against Wizardry: The Adventures of Fafhrd and the Gray Mouser', '474');
insert into book (title, duration) values ('Judas Unchained', '2458');
insert into book (title, duration) values ('Atkins Diabetes Revolution: The Groundbreaking Approach to Preventing and Controlling Type 2 Diabetes', '290');
insert into book (title, duration) values ('Pandora''s Star', '2241');
insert into book (title, duration) values ('The Swords of Lankhmar: The Adventures of Fafhrd and the Gray Mouser', '616');
insert into book (title, duration) values ('Star Wars: Fate of the Jedi: Allies', '803');
insert into book (title, duration) values ('Endymion', '1397');
insert into book (title, duration) values ('The Rise of Endymion', '1788');
insert into book (title, duration) values ('Star Wars: Fate of the Jedi: Backlash', '670');
insert into book (title, duration) values ('The Fall of Hyperion', '1305');
insert into book (title, duration) values ('Hyperion', '1244');
insert into book (title, duration) values ('Once Dead, Twice Shy: Madison Avery, Book 1', '359');
insert into book (title, duration) values ('Rip Van Winkle', '40');
insert into book (title, duration) values ('The True History of Little Golden-hood', '9');
insert into book (title, duration) values ('Beauty and the Beast', '51');



insert into author (first_name, last_name) values ('Aaron', 'Allston');
insert into author (first_name, last_name) values ('Alastair', 'Reynolds');
insert into author (first_name, last_name) values ('Allen M.', 'Steele');
insert into author (first_name, last_name) values ('Andre', 'Norton');
insert into author (first_name, last_name) values ('Andrew', 'Lang');
insert into author (first_name, last_name) values ('Arthur C.', 'Clarke');
insert into author (first_name, last_name) values ('B.V.', 'Larson');
insert into author (first_name, last_name) values ('Ben', 'Shapiro');
insert into author (first_name, last_name) values ('Betsy', 'Mitchell');
insert into author (first_name, last_name) values ('Bob', 'Mayer');
insert into author (first_name, last_name) values ('Brandon', 'Sanderson');
insert into author (first_name, last_name) values ('Brian', 'Greene');
insert into author (first_name, last_name) values ('Brian', 'Herbert');
insert into author (first_name, last_name) values ('Broken', 'Angels');
insert into author (first_name, last_name) values ('C. E.', 'Murphy');
insert into author (first_name, last_name) values ('Charlaine', 'Harris');
insert into author (first_name, last_name) values ('Christie', 'Golden');
insert into author (first_name, last_name) values ('Craig', 'Alanson');
insert into author (first_name, last_name) values ('Dan', 'Simmons');
insert into author (first_name, last_name) values ('Daniel H.', 'Wilson');
insert into author (first_name, last_name) values ('Dante', 'Alighieri');
insert into author (first_name, last_name) values ('Dennis E.', 'Taylor');
insert into author (first_name, last_name) values ('Diana', 'Rowland');
insert into author (first_name, last_name) values ('Drew', 'Karpyshyn');
insert into author (first_name, last_name) values ('Edgar Rice', 'Burroughs');
insert into author (first_name, last_name) values ('Eric A.', 'Radulski');
insert into author (first_name, last_name) values ('Fritz', 'Leiber');
insert into author (first_name, last_name) values ('Garon', 'Whited');
insert into author (first_name, last_name) values ('Ian R.', 'MacLeod');
insert into author (first_name, last_name) values ('J. R. R.', 'Tolkien');
insert into author (first_name, last_name) values ('J. S.', 'Morin');
insert into author (first_name, last_name) values ('Jack', 'McDevitt');
insert into author (first_name, last_name) values ('Jacqueline A.', 'Eberstein');
insert into author (first_name, last_name) values ('James', 'Luceno');
insert into author (first_name, last_name) values ('Jay', 'Bonansinga');
insert into author (first_name, last_name) values ('Jeremy', 'Robinson');
insert into author (first_name, last_name) values ('Jerry', 'Merritt');
insert into author (first_name, last_name) values ('Jerry', 'Pournelle');
insert into author (first_name, last_name) values ('Joan Frances', 'Turner');
insert into author (first_name, last_name) values ('Joe', 'Schreiber');
insert into author (first_name, last_name) values ('John', 'Barnes');
insert into author (first_name, last_name) values ('John', 'Birmingham');
insert into author (first_name, last_name) values ('John David', 'Krygelski');
insert into author (first_name, last_name) values ('John Jackson', 'Miller');
insert into author (first_name, last_name) values ('John', 'O''Brien');
insert into author (first_name, last_name) values ('John', 'Scalzi');
insert into author (first_name, last_name) values ('John', 'Sonmez');
insert into author (first_name, last_name) values ('Karen', 'Traviss');
insert into author (first_name, last_name) values ('Kevin J.', 'Anderson');
insert into author (first_name, last_name) values ('Kim', 'Harrison');
insert into author (first_name, last_name) values ('Larry', 'Niven');
insert into author (first_name, last_name) values ('Lee', 'Smolin');
insert into author (first_name, last_name) values ('Leonard', 'Susskind');
insert into author (first_name, last_name) values ('Margaret Wander', 'Bonnanno');
insert into author (first_name, last_name) values ('Margaret', 'Weis');
insert into author (first_name, last_name) values ('Mark', 'Tufo');
insert into author (first_name, last_name) values ('Martha', 'Stout');
insert into author (first_name, last_name) values ('Mary C.', 'Vernon');
insert into author (first_name, last_name) values ('Michael', 'Crichton');
insert into author (first_name, last_name) values ('Michael', 'Moorcock');
insert into author (first_name, last_name) values ('Michael', 'Swanwick');
insert into author (first_name, last_name) values ('Michelle', 'Rowen');
insert into author (first_name, last_name) values ('Molly', 'Harper');
insert into author (first_name, last_name) values ('Nancy', 'Kress');
insert into author (first_name, last_name) values ('Paul S.', 'Kemp');
insert into author (first_name, last_name) values ('Peter F.', 'Hamilton');
insert into author (first_name, last_name) values ('R. A.', 'Salvatore');
insert into author (first_name, last_name) values ('R. R.', 'Haywood');
insert into author (first_name, last_name) values ('Rachel', 'Aaron');
insert into author (first_name, last_name) values ('Richard K.', 'Morgan');
insert into author (first_name, last_name) values ('Richard', 'Kadrey');
insert into author (first_name, last_name) values ('Robert C.', 'Atkins');
insert into author (first_name, last_name) values ('Robert', 'Doherty');
insert into author (first_name, last_name) values ('Robert', 'Jordan');
insert into author (first_name, last_name) values ('Robert', 'Kirkman');
insert into author (first_name, last_name) values ('Robert', 'Silverberg');
insert into author (first_name, last_name) values ('Rysa', 'Walker');
insert into author (first_name, last_name) values ('Scott', 'Lynch');
insert into author (first_name, last_name) values ('Sean', 'Williams');
insert into author (first_name, last_name) values ('Stefan', 'Petrucha');
insert into author (first_name, last_name) values ('Stephen', 'Baxter');
insert into author (first_name, last_name) values ('Steven', 'Sherrill');
insert into author (first_name, last_name) values ('TW', 'Brown');
insert into author (first_name, last_name) values ('Terry', 'Pratchett');
insert into author (first_name, last_name) values ('Tim', 'Lebbon');
insert into author (first_name, last_name) values ('Timothy', 'Zahn');
insert into author (first_name, last_name) values ('Tom', 'Purdom');
insert into author (first_name, last_name) values ('Tracy', 'Hickman');
insert into author (first_name, last_name) values ('Travis', 'Adkins');
insert into author (first_name, last_name) values ('Troy', 'Denning');
insert into author (first_name, last_name) values ('Washington', 'Irving');
insert into author (first_name, last_name) values ('Wayne', 'Barlowe');
insert into author (first_name, last_name) values ('Yahtzee', 'Croshaw');
insert into author (first_name, last_name) values ('Z. A.', 'Recht');


insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Fifth Elephant'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Columbus Day: Expeditionary Force, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Craig Alanson'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lycan Fallout 5: Demon Wars'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Redemption Ark'), (select author_id from author where first_name || ' ' || last_name = 'Alastair Reynolds'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Salvation: Salvation Sequence, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Void: Nightlord, Book 5'), (select author_id from author where first_name || ' ' || last_name = 'Garon Whited'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Hollywood Dead: A Sandman Slim Novel: Sandman Slim Series, Book 10'), (select author_id from author where first_name || ' ' || last_name = 'Richard Kadrey'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Infinite'), (select author_id from author where first_name || ' ' || last_name = 'Jeremy Robinson'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Valhalla: A Shrouded World, Book 4'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Valhalla: A Shrouded World, Book 4'), (select author_id from author where first_name || ' ' || last_name = 'John O''Brien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Etna Station: Zombie Fallout, Book 11'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Naked God: Night''s Dawn Trilogy, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Extinct: Extracted, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'R. R. Haywood'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Differently Morphous'), (select author_id from author where first_name || ' ' || last_name = 'Yahtzee Croshaw'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Galaxy Outlaws: The Complete Black Ocean Mobius Missions, 1-16.5'), (select author_id from author where first_name || ' ' || last_name = 'J. S. Morin'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Mogworld'), (select author_id from author where first_name || ' ' || last_name = 'Yahtzee Croshaw'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Broken Angels'), (select author_id from author where first_name || ' ' || last_name = 'Richard K. Morgan'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'A Gift of Time'), (select author_id from author where first_name || ' ' || last_name = 'Jerry Merritt'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Altered Carbon'), (select author_id from author where first_name || ' ' || last_name = 'Richard K. Morgan'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Neutronium Alchemist: The Night''s Dawn Trilogy, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Executed: Extracted, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'R. R. Haywood'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Extracted: Extracted, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'R. R. Haywood'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Defeat''s Victory'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));

insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Bullies: How the Left''s Culture of Fear and Intimidation Silences Americans'), (select author_id from author where first_name || ' ' || last_name = 'Ben Shapiro'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Last Continent'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Convergence: A Shrouded World, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'John O''Brien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Convergence: A Shrouded World, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Demon Fallout: The Return'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Victory''s Defeat'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Into the Fire'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'From The Ashes'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'We Are Legion (We Are Bob): Bobiverse, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Dennis E. Taylor'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Reckoning'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Indian Hill'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'DEAD: The Ugly Beginning'), (select author_id from author where first_name || ' ' || last_name = 'TW Brown'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'My Life as a White Trash Zombie'), (select author_id from author where first_name || ' ' || last_name = 'Diana Rowland'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Dangers of Dating a Rebound Vampire'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Those Left Behind: Zombie Fallout 10'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Integral Trees: The State, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Larry Niven'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Barsoom Series Collection: 7 John Carter Stories'), (select author_id from author where first_name || ' ' || last_name = 'Edgar Rice Burroughs'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Knightfall: Nightlord, Book 4'), (select author_id from author where first_name || ' ' || last_name = 'Garon Whited'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Soft Skills: The Software Developer''s Life Manual'), (select author_id from author where first_name || ' ' || last_name = 'John Sonmez'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Timebound'), (select author_id from author where first_name || ' ' || last_name = 'Rysa Walker'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Night Shift'), (select author_id from author where first_name || ' ' || last_name = 'Charlaine Harris'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Tim2: Timothy'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Hogfather'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lycan Fallout 4: Immortality''s Touchstone'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Taken: A New World, Book 4'), (select author_id from author where first_name || ' ' || last_name = 'John O''Brien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Feet of Clay'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Maskerade'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));

insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Interesting Times'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Revelation Space'), (select author_id from author where first_name || ' ' || last_name = 'Alastair Reynolds'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Mindstar Rising: The Greg Mandel Trilogy, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'A Night Without Stars: A Novel of the Commonwealth: Chronicle of the Fallers Series, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Orb: Nightlord, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'Garon Whited'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Reality Dysfunction: Night''s Dawn Trilogy, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Soul Music'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'After Twilight: Walking with the Dead'), (select author_id from author where first_name || ' ' || last_name = 'Travis Adkins'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lycan Fallout 3: End of Age'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Men at Arms'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Sanctuary: A New World, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'John O''Brien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Footfall'), (select author_id from author where first_name || ' ' || last_name = 'Larry Niven'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Footfall'), (select author_id from author where first_name || ' ' || last_name = 'Jerry Pournelle'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Gripping Hand'), (select author_id from author where first_name || ' ' || last_name = 'Jerry Pournelle'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Gripping Hand'), (select author_id from author where first_name || ' ' || last_name = 'Larry Niven'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lords and Ladies'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Killing Pretty: A Sandman Slim Novel'), (select author_id from author where first_name || ' ' || last_name = 'Richard Kadrey'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Abyss Beyond Dreams: Chronicle of the Fallers, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Starfire'), (select author_id from author where first_name || ' ' || last_name = 'B.V. Larson'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Small Gods: Discworld #13'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'RETURN: A New World: Book 2'), (select author_id from author where first_name || ' ' || last_name = 'John O''Brien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Shadows: Nightlord, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Garon Whited'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Witches Abroad'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Tattered Remnants: Zombie Fallout 9'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Nightlord: Sunset'), (select author_id from author where first_name || ' ' || last_name = 'Garon Whited'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Chaos: A New World: Book 1'), (select author_id from author where first_name || ' ' || last_name = 'John O''Brien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Atlantis: A Shrouded World, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Atlantis: A Shrouded World, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'John O''Brien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Whistlers: A Shrouded World, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Whistlers: A Shrouded World, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'John O''Brien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Carrion Comfort'), (select author_id from author where first_name || ' ' || last_name = 'Dan Simmons'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Dune: The Battle of Corrin'), (select author_id from author where first_name || ' ' || last_name = 'Brian Herbert'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Dune: The Battle of Corrin'), (select author_id from author where first_name || ' ' || last_name = 'Kevin J. Anderson'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Getaway God: Sandman Slim, Book 6'), (select author_id from author where first_name || ' ' || last_name = 'Richard Kadrey'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Snow Women: A Fafhrd and the Gray Mouser Adventure'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Adept''s Gambit: A Fafhrd and the Gray Mouser Adventure'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Lords of Quarmall: A Fafhrd and the Gray Mouser Adventure'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Rime Isle: A Fafhrd and the Gray Mouser Adventure'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Mouser Goes Below: A Fafhrd and the Gray Mouser Adventure'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Spirit Clearing: A Michael Talbot Adventure'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Reaper Man'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Moving Pictures'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lycan Fallout 2: Fall of Man'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lycan Fallout: Rise of the Werewolf'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Eric'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Guards! Guards!'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Pyramids: Discworld #7'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Wyrd Sisters'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lords of the Sith: Star Wars'), (select author_id from author where first_name || ' ' || last_name = 'Paul S. Kemp'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Sourcery'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Mort'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Zombie Fallout 8: An Old Beginning'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Zombie Fallout 7: For The Fallen'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Equal Rites'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lucifer''s Hammer'), (select author_id from author where first_name || ' ' || last_name = 'Larry Niven'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Lucifer''s Hammer'), (select author_id from author where first_name || ' ' || last_name = 'Jerry Pournelle'));


insert into book_author (book_id, author_id) values ((select book_id from book where title = '''Til Death Do Us Part: Zombie Fallout, Book 6'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Mote in God''s Eye'), (select author_id from author where first_name || ' ' || last_name = 'Larry Niven'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Mote in God''s Eye'), (select author_id from author where first_name || ' ' || last_name = 'Jerry Pournelle'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Zombie Fallout 5: Alive in a Dead World'), (select author_id from author where first_name || ' ' || last_name = 'Mark Tufo'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Light Fantastic: Discworld #2'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Annihilation: Star Wars: The Old Republic, Book 4'), (select author_id from author where first_name || ' ' || last_name = 'Drew Karpyshyn'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Undead Pool: The Hollows, Book 12'), (select author_id from author where first_name || ' ' || last_name = 'Kim Harrison'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Timeless Time Travel Tales'), (select author_id from author where first_name || ' ' || last_name = 'John Barnes'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Timeless Time Travel Tales'), (select author_id from author where first_name || ' ' || last_name = 'Nancy Kress'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Timeless Time Travel Tales'), (select author_id from author where first_name || ' ' || last_name = 'Ian R. MacLeod'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Timeless Time Travel Tales'), (select author_id from author where first_name || ' ' || last_name = 'Tom Purdom'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Timeless Time Travel Tales'), (select author_id from author where first_name || ' ' || last_name = 'Robert Silverberg'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Timeless Time Travel Tales'), (select author_id from author where first_name || ' ' || last_name = 'Allen M. Steele'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Timeless Time Travel Tales'), (select author_id from author where first_name || ' ' || last_name = 'Michael Swanwick'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Witch with No Name: The Hollows, Book 13'), (select author_id from author where first_name || ' ' || last_name = 'Kim Harrison'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Dark Lord: The Rise of Darth Vader'), (select author_id from author where first_name || ' ' || last_name = 'James Luceno'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: The Old Republic: Revan'), (select author_id from author where first_name || ' ' || last_name = 'Drew Karpyshyn'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Republic of Thieves: Gentleman Bastard Series, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'Scott Lynch'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Trek: Probe (Adapted)'), (select author_id from author where first_name || ' ' || last_name = 'Margaret Wander Bonnanno'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Time Cursor'), (select author_id from author where first_name || ' ' || last_name = 'John David Krygelski'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Redshirts: A Novel with Three Codas'), (select author_id from author where first_name || ' ' || last_name = 'John Scalzi'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Maul: Lockdown'), (select author_id from author where first_name || ' ' || last_name = 'Joe Schreiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Fall of the Governor: The Walking Dead, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'Robert Kirkman'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Fall of the Governor: The Walking Dead, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'Jay Bonansinga'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: The Old Republic: Deceived'), (select author_id from author where first_name || ' ' || last_name = 'Paul S. Kemp'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Kenobi: Star Wars Legends'), (select author_id from author where first_name || ' ' || last_name = 'John Jackson Miller'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Darth Plagueis'), (select author_id from author where first_name || ' ' || last_name = 'James Luceno'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Dynasty of Evil: A Novel of the Old Republic'), (select author_id from author where first_name || ' ' || last_name = 'Drew Karpyshyn'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Rule of Two: Star Wars Legends (Darth Bane)'), (select author_id from author where first_name || ' ' || last_name = 'Drew Karpyshyn'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Allegiance: Star Wars Legends'), (select author_id from author where first_name || ' ' || last_name = 'Timothy Zahn'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Red Harvest'), (select author_id from author where first_name || ' ' || last_name = 'Joe Schreiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Robopocalypse: A Novel'), (select author_id from author where first_name || ' ' || last_name = 'Daniel H. Wilson'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Apocalypse: Star Wars Legends (Fate of the Jedi)'), (select author_id from author where first_name || ' ' || last_name = 'Troy Denning'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Path of Destruction: Star Wars Legends (Darth Bane)'), (select author_id from author where first_name || ' ' || last_name = 'Drew Karpyshyn'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Into the Void: Star Wars Legends (Dawn of the Jedi)'), (select author_id from author where first_name || ' ' || last_name = 'Tim Lebbon'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Care and Feeding of Stray Vampires'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: The Clone Wars: No Prisoners'), (select author_id from author where first_name || ' ' || last_name = 'Karen Traviss'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Bloodlust: Nightshade Series, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Michelle Rowen'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Free Excerpt: Star Wars: Heir to the Empire - Behind the Scenes'), (select author_id from author where first_name || ' ' || last_name = 'Timothy Zahn'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Free Excerpt: Star Wars: Heir to the Empire - Behind the Scenes'), (select author_id from author where first_name || ' ' || last_name = 'Betsy Mitchell'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'A Memory of Light: Wheel of Time, Book 14'), (select author_id from author where first_name || ' ' || last_name = 'Robert Jordan'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'A Memory of Light: Wheel of Time, Book 14'), (select author_id from author where first_name || ' ' || last_name = 'Brandon Sanderson'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Twilight of the Dead'), (select author_id from author where first_name || ' ' || last_name = 'Travis Adkins'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Walking Dead: The Road to Woodbury'), (select author_id from author where first_name || ' ' || last_name = 'Robert Kirkman'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Walking Dead: The Road to Woodbury'), (select author_id from author where first_name || ' ' || last_name = 'Jay Bonansinga'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Urban Shaman: The Walker Papers, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'C. E. Murphy'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Colour of Magic: Discworld #1'), (select author_id from author where first_name || ' ' || last_name = 'Terry Pratchett'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Dust'), (select author_id from author where first_name || ' ' || last_name = 'Joan Frances Turner'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Plague of the Dead: The Morningstar Strain, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Z. A. Recht'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'World of Ptavvs'), (select author_id from author where first_name || ' ' || last_name = 'Larry Niven'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Time Hunter: The Tunnel at the End of the Light'), (select author_id from author where first_name || ' ' || last_name = 'Stefan Petrucha'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Area 51'), (select author_id from author where first_name || ' ' || last_name = 'Bob Mayer'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Area 51'), (select author_id from author where first_name || ' ' || last_name = 'Robert Doherty'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Time Travelers Never Die'), (select author_id from author where first_name || ' ' || last_name = 'Jack McDevitt'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Time Traders'), (select author_id from author where first_name || ' ' || last_name = 'Andre Norton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Time''s Eye: A Time Odyssey, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Arthur C. Clarke'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Time''s Eye: A Time Odyssey, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Stephen Baxter'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Final Impact: Axis of Time, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'John Birmingham'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Designated Targets: Axis of Time, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'John Birmingham'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Weapons of Choice: Axis of Time, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'John Birmingham'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'God’s Demon'), (select author_id from author where first_name || ' ' || last_name = 'Wayne Barlowe'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Nightshade: Nightshade Series, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Michelle Rowen'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Minotaur Takes a Cigarette Break: A Novel'), (select author_id from author where first_name || ' ' || last_name = 'Steven Sherrill'));



insert into book_author (book_id, author_id) values ((select book_id from book where title = 'How to Flirt with a Naked Werewolf'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Nice Girls Don''t Bite Their Neighbors: Half-Moon Hollow, Book 4'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Driving Mr. Dead'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: The Old Republic: Fatal Alliance'), (select author_id from author where first_name || ' ' || last_name = 'Sean Williams'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Elric of Melnibone'), (select author_id from author where first_name || ' ' || last_name = 'Michael Moorcock'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Dragons of the Highlord Skies: The Lost Chronicles, Volume 2'), (select author_id from author where first_name || ' ' || last_name = 'Margaret Weis'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Dragons of the Highlord Skies: The Lost Chronicles, Volume 2'), (select author_id from author where first_name || ' ' || last_name = 'Tracy Hickman'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Nice Girls Don''t Date Dead Men: Half-Moon Hollow, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Nice Girls Don''t Live Forever: Half-Moon Hollow, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Art of Seducing a Naked Werewolf'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Dragons of the Dwarven Depths: The Lost Chronicles, Volume 1'), (select author_id from author where first_name || ' ' || last_name = 'Margaret Weis'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Dragons of the Dwarven Depths: The Lost Chronicles, Volume 1'), (select author_id from author where first_name || ' ' || last_name = 'Tracy Hickman'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Demon Hunts'), (select author_id from author where first_name || ' ' || last_name = 'C. E. Murphy'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Fate of the Jedi: Conviction'), (select author_id from author where first_name || ' ' || last_name = 'Aaron Allston'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Fate of the Jedi: Ascension'), (select author_id from author where first_name || ' ' || last_name = 'Christie Golden'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Nice Girls Don''t Have Fangs: Half-Moon Hollow, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Molly Harper'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Trouble with Physics: The Rise of String Theory, The Fall of a Science, and What Comes Next'), (select author_id from author where first_name || ' ' || last_name = 'Lee Smolin'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Black Hole War: My Battle to Make the World Safe for Quantum Mechanics'), (select author_id from author where first_name || ' ' || last_name = 'Leonard Susskind'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Spirit Thief'), (select author_id from author where first_name || ' ' || last_name = 'Rachel Aaron'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Pale Demon: The Hollows, Book 9'), (select author_id from author where first_name || ' ' || last_name = 'Kim Harrison'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Next'), (select author_id from author where first_name || ' ' || last_name = 'Michael Crichton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Early to Death, Early to Rise: Madison Avery, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Kim Harrison'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Children of Hurin'), (select author_id from author where first_name || ' ' || last_name = 'J. R. R. Tolkien'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Fate of the Jedi: Vortex'), (select author_id from author where first_name || ' ' || last_name = 'Troy Denning'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Bastion of Darkness'), (select author_id from author where first_name || ' ' || last_name = 'R. A. Salvatore'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Demon Hunter''s Apprentice'), (select author_id from author where first_name || ' ' || last_name = 'Eric A. Radulski'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Sociopath Next Door'), (select author_id from author where first_name || ' ' || last_name = 'Martha Stout'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Swords and Ice Magic: The Adventures of Fafhrd and the Gray Mouser'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Knight and Knave of Swords: The Adventures of Fafhrd and the Gray Mouser'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Elegant Universe: Superstrings, Hidden Dimensions, and the Quest for the Ultimate Theory'), (select author_id from author where first_name || ' ' || last_name = 'Brian Greene'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Temporal Void: Void Trilogy, Book 2'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Evolutionary Void: Void Trilogy, Book 3'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Great Hunt: Book Two of The Wheel Of Time'), (select author_id from author where first_name || ' ' || last_name = 'Robert Jordan'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Dreaming Void: Void Trilogy, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Divine Comedy'), (select author_id from author where first_name || ' ' || last_name = 'Dante Alighieri'));
-- insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Divine Comedy'), (select author_id from author where first_name || ' ' || last_name = 'Henry Wadsworth Longfellow'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Eye of the World: Book One of The Wheel of Time'), (select author_id from author where first_name || ' ' || last_name = 'Robert Jordan'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Swords Against Wizardry: The Adventures of Fafhrd and the Gray Mouser'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Judas Unchained'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Atkins Diabetes Revolution: The Groundbreaking Approach to Preventing and Controlling Type 2 Diabetes'), (select author_id from author where first_name || ' ' || last_name = 'Robert C. Atkins'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Atkins Diabetes Revolution: The Groundbreaking Approach to Preventing and Controlling Type 2 Diabetes'), (select author_id from author where first_name || ' ' || last_name = 'Mary C. Vernon'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Atkins Diabetes Revolution: The Groundbreaking Approach to Preventing and Controlling Type 2 Diabetes'), (select author_id from author where first_name || ' ' || last_name = 'Jacqueline A. Eberstein'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Pandora''s Star'), (select author_id from author where first_name || ' ' || last_name = 'Peter F. Hamilton'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Swords of Lankhmar: The Adventures of Fafhrd and the Gray Mouser'), (select author_id from author where first_name || ' ' || last_name = 'Fritz Leiber'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Fate of the Jedi: Allies'), (select author_id from author where first_name || ' ' || last_name = 'Christie Golden'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Endymion'), (select author_id from author where first_name || ' ' || last_name = 'Dan Simmons'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Rise of Endymion'), (select author_id from author where first_name || ' ' || last_name = 'Dan Simmons'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Star Wars: Fate of the Jedi: Backlash'), (select author_id from author where first_name || ' ' || last_name = 'Aaron Allston'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The Fall of Hyperion'), (select author_id from author where first_name || ' ' || last_name = 'Dan Simmons'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Hyperion'), (select author_id from author where first_name || ' ' || last_name = 'Dan Simmons'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Once Dead, Twice Shy: Madison Avery, Book 1'), (select author_id from author where first_name || ' ' || last_name = 'Kim Harrison'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Rip Van Winkle'), (select author_id from author where first_name || ' ' || last_name = 'Washington Irving'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'The True History of Little Golden-hood'), (select author_id from author where first_name || ' ' || last_name = 'Andrew Lang'));
insert into book_author (book_id, author_id) values ((select book_id from book where title = 'Beauty and the Beast'), (select author_id from author where first_name || ' ' || last_name = 'Andrew Lang'));


